CREATE TABLE LOGIN(
ID INT AUTO_INCREMENT PRIMARY KEY,
ROL ENUM('BIBLIOTECARIO','ADMIN') DEFAULT'BIBLIOTECARIO',
USUARIO VARCHAR(80) NOT NULL,
PASS VARCHAR(80) NOT NULL
);

CREATE TABLE GENEROS (
ID_GEN INT AUTO_INCREMENT PRIMARY KEY,
GENERO VARCHAR(80) NOT NULL
);

CREATE TABLE AUTOR (
ID_AUT INT AUTO_INCREMENT PRIMARY KEY,
AUTOR VARCHAR(80) NOT NULL
);

CREATE TABLE LIBROS (
ID_LIBRO INT AUTO_INCREMENT PRIMARY KEY,
AUTOR_ID INT NOT NULL,
NOMBRE VARCHAR(80) NOT NULL,
FECHA_PUBLI DATE,
GENERO_ID INT NOT NULL,
STOCK INT,
FOREIGN KEY (GENERO_ID) REFERENCES GENEROS(ID_GEN),
FOREIGN KEY (AUTOR_ID) REFERENCES AUTOR(ID_AUT)
);

CREATE TABLE DETLIBROS(
IDDETLIB INT AUTO_INCREMENT PRIMARY KEY,
ID_LIBRO INT NOT NULL,
ESTADO ENUM('PERDIDO','MAL ESTADO','REGULAR','BUEN ESTADO','NUEVO') DEFAULT 'NUEVO',
FOREIGN KEY(ID_LIBRO) REFERENCES LIBROS(ID_LIBRO)
);

CREATE TABLE USUARIO(
ID_USU INT AUTO_INCREMENT PRIMARY KEY,
DNI CHAR(8) NOT NULL UNIQUE,
NOMBRE VARCHAR(80) NOT NULL,
APELLIDO VARCHAR(80) NOT NULL,
ESTADO VARCHAR(10) NOT NULL
);

CREATE TABLE PRESTAMOS(
ID_PRES INT AUTO_INCREMENT PRIMARY KEY,
ID_USU INT NOT NULL,
ID_LIBRO INT NOT NULL,
FECHA_PRES DATE,
FECHA_DEV DATE,
DEVUELTO CHAR(2) DEFAULT 'NO' NOT NULL,
FOREIGN KEY(ID_USU) REFERENCES USUARIO(ID_USU),
FOREIGN KEY(ID_LIBRO) REFERENCES DETLIBROS(IDDETLIB)
);

INSERT INTO LOGIN (ROL,USUARIO,PASS) VALUES('ADMIN','admin','admin');